name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - uses: dschep/install-poetry-action@v1.2    
    - name: install dependencies
      run: make install
    - name: change to virtual env
      run: poetry shell
    - name: clean build
      run: make clean build
